// Comprehensive Astronomical Events JSON Data
const COMPREHENSIVE_ASTRO_DATA = {
  // Location data for 50+ major cities worldwide
  locations: [
    // Asia
    { lat: 35.68, lon: 139.76, name: "Tokyo, Japan" },
    { lat: 39.9, lon: 116.41, name: "Beijing, China" },
    { lat: 22.32, lon: 114.17, name: "Hong Kong, China" },
    { lat: 1.35, lon: 103.82, name: "Singapore" },
    { lat: 13.75, lon: 100.5, name: "Bangkok, Thailand" },
    { lat: 37.57, lon: 126.98, name: "Seoul, South Korea" },
    { lat: 25.2, lon: 55.27, name: "Dubai, UAE" },
    { lat: 19.08, lon: 72.88, name: "Mumbai, India" },
    { lat: 28.61, lon: 77.21, name: "New Delhi, India" },
    { lat: 6.93, lon: 79.85, name: "Colombo, Sri Lanka" },

    // Europe
    { lat: 51.51, lon: -0.13, name: "London, UK" },
    { lat: 48.86, lon: 2.35, name: "Paris, France" },
    { lat: 52.52, lon: 13.41, name: "Berlin, Germany" },
    { lat: 41.9, lon: 12.5, name: "Rome, Italy" },
    { lat: 55.76, lon: 37.62, name: "Moscow, Russia" },
    { lat: 59.33, lon: 18.07, name: "Stockholm, Sweden" },
    { lat: 52.37, lon: 4.89, name: "Amsterdam, Netherlands" },
    { lat: 41.01, lon: 28.98, name: "Istanbul, Turkey" },
    { lat: 50.08, lon: 14.44, name: "Prague, Czech Republic" },
    { lat: 40.42, lon: -3.7, name: "Madrid, Spain" },

    // North America
    { lat: 40.71, lon: -74.01, name: "New York, USA" },
    { lat: 34.05, lon: -118.24, name: "Los Angeles, USA" },
    { lat: 41.88, lon: -87.63, name: "Chicago, USA" },
    { lat: 43.65, lon: -79.38, name: "Toronto, Canada" },
    { lat: 49.28, lon: -123.12, name: "Vancouver, Canada" },
    { lat: 19.43, lon: -99.13, name: "Mexico City, Mexico" },
    { lat: 25.76, lon: -80.19, name: "Miami, USA" },
    { lat: 47.61, lon: -122.33, name: "Seattle, USA" },
    { lat: 39.74, lon: -104.99, name: "Denver, USA" },
    { lat: 33.45, lon: -112.07, name: "Phoenix, USA" },

    // South America
    { lat: -22.91, lon: -43.21, name: "Rio de Janeiro, Brazil" },
    { lat: -15.78, lon: -47.93, name: "Brasília, Brazil" },
    { lat: -34.6, lon: -58.38, name: "Buenos Aires, Argentina" },
    { lat: -12.05, lon: -77.04, name: "Lima, Peru" },
    { lat: -33.45, lon: -70.67, name: "Santiago, Chile" },
    { lat: 4.71, lon: -74.07, name: "Bogotá, Colombia" },
    { lat: -0.18, lon: -78.47, name: "Quito, Ecuador" },

    // Africa
    { lat: -33.87, lon: 151.21, name: "Sydney, Australia" },
    { lat: -37.81, lon: 144.96, name: "Melbourne, Australia" },
    { lat: -31.95, lon: 115.86, name: "Perth, Australia" },
    { lat: -36.85, lon: 174.76, name: "Auckland, New Zealand" },
    { lat: -1.29, lon: 36.82, name: "Nairobi, Kenya" },
    { lat: 30.04, lon: 31.24, name: "Cairo, Egypt" },
    { lat: -26.2, lon: 28.04, name: "Johannesburg, South Africa" },
    { lat: 5.56, lon: -0.2, name: "Accra, Ghana" },
    { lat: 6.45, lon: 3.39, name: "Lagos, Nigeria" },

    // Special locations for astronomy
    { lat: 19.82, lon: -155.47, name: "Mauna Kea Observatory, Hawaii" },
    { lat: -29.26, lon: -70.73, name: "La Silla Observatory, Chile" },
    { lat: 28.76, lon: -17.89, name: "Roque de los Muchachos, Spain" },
    {
      lat: -32.38,
      lon: 20.81,
      name: "Sutherland Observatory, South Africa",
    },
    { lat: 31.67, lon: 35.24, name: "Wise Observatory, Israel" },
  ],

  // Comprehensive Astronomical Events (2024-2027)
  astronomicalEvents: {
    // All Moon Phases for next 3 years (representative sample)
    moon_phases: [
      // Current and upcoming phases
      {
        id: "moon_current",
        title: "Current Moon Phase",
        date: new Date().toISOString(),
        type: "moon_phase",
        description: "Real-time moon illumination",
        phase: null, // Will be calculated
        illumination: null,
      },
      {
        id: "new_moon_2024_11",
        title: "New Moon",
        date: "2024-12-01T06:21:00Z",
        type: "moon_phase",
        description: "Moon not visible",
        phase: 0,
        illumination: 0,
      },
      {
        id: "first_quarter_2024_11",
        title: "First Quarter Moon",
        date: "2024-12-08T15:27:00Z",
        type: "moon_phase",
        description: "Right half illuminated",
        phase: 0.25,
        illumination: 0.5,
      },
      {
        id: "full_moon_2024_12",
        title: "Full Moon (Cold Moon)",
        date: "2024-12-15T09:02:00Z",
        type: "moon_phase",
        description: "Completely illuminated",
        phase: 0.5,
        illumination: 1.0,
      },
      {
        id: "last_quarter_2024_12",
        title: "Last Quarter Moon",
        date: "2024-12-22T22:18:00Z",
        type: "moon_phase",
        description: "Left half illuminated",
        phase: 0.75,
        illumination: 0.5,
      },
      {
        id: "new_moon_2025_01",
        title: "New Moon",
        date: "2025-01-29T12:36:00Z",
        type: "moon_phase",
        description: "Moon not visible",
        phase: 0,
        illumination: 0,
      },
      {
        id: "super_moon_2025_11",
        title: "Supermoon (Perigee Full Moon)",
        date: "2025-11-05T13:19:00Z",
        type: "moon_phase",
        description: "Closest and brightest full moon of year",
        phase: 0.5,
        illumination: 1.0,
        special: "supermoon",
      },
      {
        id: "blue_moon_2026_05",
        title: "Blue Moon",
        date: "2026-05-31T08:45:00Z",
        type: "moon_phase",
        description: "Second full moon in calendar month",
        phase: 0.5,
        illumination: 1.0,
        special: "blue_moon",
      },
    ],

    // Solar Eclipses 2024-2027
    solar_eclipses: [
      {
        id: "solar_2024_10",
        title: "Annular Solar Eclipse",
        date: "2024-10-02T18:46:00Z",
        type: "solar_eclipse",
        description: "Ring of Fire eclipse",
        subtype: "annular",
        magnitude: 0.932,
        duration: "7m 25s",
        path: {
          centerLon: -95,
          centerLat: 40,
          radius: 200,
          coordinates: [
            [-115, 60],
            [-110, 55],
            [-100, 45],
            [-90, 30],
            [-80, 15],
          ],
        },
        visibility_regions: ["North America", "Pacific"],
      },
      {
        id: "solar_2025_03",
        title: "Total Solar Eclipse",
        date: "2025-03-29T10:48:00Z",
        type: "solar_eclipse",
        description: "Path across North Atlantic",
        subtype: "total",
        magnitude: 1.056,
        duration: "4m 26s",
        path: {
          centerLon: -30,
          centerLat: 60,
          radius: 150,
          coordinates: [
            [-60, 75],
            [-45, 65],
            [-30, 55],
            [-15, 45],
            [0, 35],
          ],
        },
        visibility_regions: ["Greenland", "Iceland", "Spain", "Portugal"],
      },
      {
        id: "solar_2026_08",
        title: "Total Solar Eclipse",
        date: "2026-08-12T17:47:00Z",
        type: "solar_eclipse",
        description: "Path across Arctic, Europe, and Africa",
        subtype: "total",
        magnitude: 1.039,
        duration: "6m 23s",
        path: {
          centerLon: 15,
          centerLat: 70,
          radius: 180,
          coordinates: [
            [-10, 80],
            [5, 75],
            [20, 70],
            [35, 60],
            [50, 40],
          ],
        },
        visibility_regions: ["Arctic", "Europe", "North Africa"],
      },
      {
        id: "solar_2027_02",
        title: "Annular Solar Eclipse",
        date: "2027-02-06T16:00:00Z",
        type: "solar_eclipse",
        description: "Across South America and Africa",
        subtype: "annular",
        magnitude: 0.928,
        duration: "7m 51s",
        path: {
          centerLon: -40,
          centerLat: -30,
          radius: 220,
          coordinates: [
            [-60, -10],
            [-50, -20],
            [-40, -30],
            [-30, -40],
            [-20, -50],
          ],
        },
        visibility_regions: ["South America", "Africa", "Atlantic"],
      },
    ],

    // Lunar Eclipses 2024-2027
    lunar_eclipses: [
      {
        id: "lunar_2024_09",
        title: "Partial Lunar Eclipse",
        date: "2024-09-17T22:44:00Z",
        type: "lunar_eclipse",
        description: "Partial eclipse visible in Americas, Europe, Africa",
        subtype: "partial",
        magnitude: 0.064,
        duration: "4h 6m",
        path: {
          centerLon: -60,
          centerLat: 0,
          radius: 120,
        },
        visibility_regions: ["Americas", "Europe", "Africa", "Pacific"],
      },
      {
        id: "lunar_2025_03",
        title: "Total Lunar Eclipse",
        date: "2025-03-14T06:59:00Z",
        type: "lunar_eclipse",
        description: "Blood Moon visible in Pacific, Americas, East Asia",
        subtype: "total",
        magnitude: 1.178,
        duration: "5h 57m",
        path: {
          centerLon: -150,
          centerLat: 0,
          radius: 130,
        },
        visibility_regions: ["Pacific", "Americas", "East Asia", "Australia"],
      },
      {
        id: "lunar_2025_09",
        title: "Total Lunar Eclipse",
        date: "2025-09-07T18:12:00Z",
        type: "lunar_eclipse",
        description: "Blood Moon visible in Europe, Africa, Asia, Australia",
        subtype: "total",
        magnitude: 1.362,
        duration: "6h 8m",
        path: {
          centerLon: 60,
          centerLat: 0,
          radius: 125,
        },
        visibility_regions: ["Europe", "Africa", "Asia", "Australia"],
      },
      {
        id: "lunar_2026_03",
        title: "Total Lunar Eclipse",
        date: "2026-03-03T11:34:00Z",
        type: "lunar_eclipse",
        description: "Longest total lunar eclipse until 2029",
        subtype: "total",
        magnitude: 1.151,
        duration: "5h 42m",
        path: {
          centerLon: 170,
          centerLat: 10,
          radius: 110,
        },
        visibility_regions: ["Asia", "Australia", "Pacific", "Americas"],
      },
    ],

    // Major Meteor Showers
    meteor_showers: [
      {
        id: "quadrantids_2025",
        title: "Quadrantid Meteor Shower",
        date: "2025-01-03T20:00:00Z",
        type: "meteor_shower",
        description: "First major shower of the year",
        peak_rate: 120,
        constellation: "Boötes",
        best_viewing: "Northern Hemisphere",
        radiant: { ra: 230, dec: 49 },
      },
      {
        id: "lyrids_2025",
        title: "Lyrid Meteor Shower",
        date: "2025-04-22T02:00:00Z",
        type: "meteor_shower",
        description: "Known for fast, bright meteors",
        peak_rate: 18,
        constellation: "Lyra",
        best_viewing: "Both Hemispheres",
        radiant: { ra: 271, dec: 34 },
      },
      {
        id: "perseids_2025",
        title: "Perseid Meteor Shower",
        date: "2025-08-12T08:00:00Z",
        type: "meteor_shower",
        description: "Most popular meteor shower",
        peak_rate: 100,
        constellation: "Perseus",
        best_viewing: "Northern Hemisphere",
        radiant: { ra: 48, dec: 58 },
      },
      {
        id: "orionids_2025",
        title: "Orionid Meteor Shower",
        date: "2025-10-21T06:00:00Z",
        type: "meteor_shower",
        description: "Halley's Comet debris",
        peak_rate: 20,
        constellation: "Orion",
        best_viewing: "Both Hemispheres",
        radiant: { ra: 95, dec: 16 },
      },
      {
        id: "leonids_2025",
        title: "Leonid Meteor Shower",
        date: "2025-11-17T23:00:00Z",
        type: "meteor_shower",
        description: "Known for meteor storms",
        peak_rate: 15,
        constellation: "Leo",
        best_viewing: "Both Hemispheres",
        radiant: { ra: 152, dec: 22 },
      },
      {
        id: "geminids_2025",
        title: "Geminid Meteor Shower",
        date: "2025-12-14T18:00:00Z",
        type: "meteor_shower",
        description: "Rich, multi-colored meteors",
        peak_rate: 150,
        constellation: "Gemini",
        best_viewing: "Both Hemispheres",
        radiant: { ra: 112, dec: 33 },
      },
      {
        id: "ursids_2025",
        title: "Ursid Meteor Shower",
        date: "2025-12-22T09:00:00Z",
        type: "meteor_shower",
        description: "Minor shower near Ursa Minor",
        peak_rate: 10,
        constellation: "Ursa Minor",
        best_viewing: "Northern Hemisphere",
        radiant: { ra: 217, dec: 76 },
      },
    ],

    // Planetary Events (Conjunctions, Oppositions, Transits)
    planetary_events: [
      {
        id: "jupiter_opposition_2024",
        title: "Jupiter at Opposition",
        date: "2024-11-02T04:00:00Z",
        type: "planetary",
        description: "Jupiter closest to Earth, brightest of year",
        planets: ["Jupiter"],
        separation: "Opposition",
        magnitude: -2.9,
      },
      {
        id: "mars_opposition_2025",
        title: "Mars at Opposition",
        date: "2025-01-16T06:00:00Z",
        type: "planetary",
        description: "Mars closest approach until 2027",
        planets: ["Mars"],
        separation: "Opposition",
        magnitude: -1.4,
      },
      {
        id: "saturn_opposition_2025",
        title: "Saturn at Opposition",
        date: "2025-08-27T08:00:00Z",
        type: "planetary",
        description: "Best time to view Saturn's rings",
        planets: ["Saturn"],
        separation: "Opposition",
        magnitude: 0.4,
      },
      {
        id: "venus_jupiter_conjunction_2025",
        title: "Venus-Jupiter Conjunction",
        date: "2025-05-23T18:00:00Z",
        type: "planetary",
        description: "Close approach of two brightest planets",
        planets: ["Venus", "Jupiter"],
        separation: "0.2°",
        magnitude: -4.5,
      },
      {
        id: "mars_venus_conjunction_2026",
        title: "Mars-Venus Conjunction",
        date: "2026-02-12T05:00:00Z",
        type: "planetary",
        description: "Close approach in morning sky",
        planets: ["Mars", "Venus"],
        separation: "0.4°",
        magnitude: -4.2,
      },
      {
        id: "mercury_transit_2025",
        title: "Mercury Transit",
        date: "2025-11-13T12:00:00Z",
        type: "planetary",
        description: "Mercury crosses the Sun's disk",
        planets: ["Mercury"],
        duration: "5h 28m",
        magnitude: "Transit",
      },
    ],

    // Comet Apparitions
    comets: [
      {
        id: "comet_12p_2024",
        title: "Comet 12P/Pons-Brooks",
        date: "2024-04-21T00:00:00Z",
        type: "comet",
        description: "Halley-type comet with outbursts",
        magnitude: 4.5,
        constellation: "Aries",
        period: "71 years",
      },
      {
        id: "comet_t3_2025",
        title: "Comet Tsuchinshan-ATLAS",
        date: "2025-09-27T00:00:00Z",
        type: "comet",
        description: "Potentially naked-eye visible",
        magnitude: 3.0,
        constellation: "Orion",
        period: "Non-periodic",
      },
      {
        id: "comet_144p_2026",
        title: "Comet 144P/Kushida",
        date: "2026-01-15T00:00:00Z",
        type: "comet",
        description: "Short-period comet outburst",
        magnitude: 8.5,
        constellation: "Taurus",
        period: "7.6 years",
      },
    ],

    // Special Celestial Events
    special_events: [
      {
        id: "aurora_peak_2024",
        title: "Aurora Borealis Peak Season",
        date: "2024-12-21T00:00:00Z",
        type: "aurora",
        description: "Winter solstice - peak aurora activity",
        regions: ["Arctic", "Northern Europe", "Canada", "Alaska"],
        kp_index: "6-8",
      },
      {
        id: "milky_way_season_2025",
        title: "Milky Way Core Season",
        date: "2025-06-21T00:00:00Z",
        type: "star_gazing",
        description: "Best time to photograph Milky Way core",
        best_viewing: "Southern Hemisphere",
        conditions: "New Moon period",
      },
      {
        id: "zodiacal_light_2025",
        title: "Zodiacal Light Season",
        date: "2025-02-15T00:00:00Z",
        type: "zodiacal_light",
        description: "Pyramid of light visible after sunset",
        best_viewing: "Dark sky locations",
        months: ["February", "March", "September", "October"],
      },
      {
        id: "eclipse_season_2026",
        title: "Eclipse Season 2026",
        date: "2026-02-17T00:00:00Z",
        type: "eclipse_season",
        description: "Pair of solar and lunar eclipses",
        events: [
          "Annular Solar Eclipse Feb 17",
          "Penumbral Lunar Eclipse Mar 3",
        ],
        duration: "35 days",
      },
    ],
  },

  // Timezone data
  timezones: [
    { lon: -180, lonEnd: -172.5, offset: -12, name: "UTC-12" },
    { lon: -172.5, lonEnd: -157.5, offset: -11, name: "UTC-11" },
    { lon: -157.5, lonEnd: -142.5, offset: -10, name: "UTC-10" },
    { lon: -142.5, lonEnd: -127.5, offset: -9, name: "UTC-9" },
    { lon: -127.5, lonEnd: -112.5, offset: -8, name: "UTC-8" },
    { lon: -112.5, lonEnd: -97.5, offset: -7, name: "UTC-7" },
    { lon: -97.5, lonEnd: -82.5, offset: -6, name: "UTC-6" },
    { lon: -82.5, lonEnd: -67.5, offset: -5, name: "UTC-5" },
    { lon: -67.5, lonEnd: -52.5, offset: -4, name: "UTC-4" },
    { lon: -52.5, lonEnd: -37.5, offset: -3, name: "UTC-3" },
    { lon: -37.5, lonEnd: -22.5, offset: -2, name: "UTC-2" },
    { lon: -22.5, lonEnd: -7.5, offset: -1, name: "UTC-1" },
    { lon: -7.5, lonEnd: 7.5, offset: 0, name: "UTC" },
    { lon: 7.5, lonEnd: 22.5, offset: 1, name: "UTC+1" },
    { lon: 22.5, lonEnd: 37.5, offset: 2, name: "UTC+2" },
    { lon: 37.5, lonEnd: 52.5, offset: 3, name: "UTC+3" },
    { lon: 52.5, lonEnd: 67.5, offset: 4, name: "UTC+4" },
    { lon: 67.5, lonEnd: 82.5, offset: 5, name: "UTC+5" },
    { lon: 82.5, lonEnd: 97.5, offset: 5.5, name: "UTC+5:30" },
    { lon: 97.5, lonEnd: 112.5, offset: 7, name: "UTC+7" },
    { lon: 112.5, lonEnd: 127.5, offset: 8, name: "UTC+8" },
    { lon: 127.5, lonEnd: 142.5, offset: 9, name: "UTC+9" },
    { lon: 142.5, lonEnd: 157.5, offset: 10, name: "UTC+10" },
    { lon: 157.5, lonEnd: 172.5, offset: 11, name: "UTC+11" },
    { lon: 172.5, lonEnd: 180, offset: 12, name: "UTC+12" },
  ],
};
